### ISSUE TITLE
Возможное исправление ошибки при установке paambaati/codeclimate-action@v3

### ISSUE THREAD

**Issue by gomez-git** [hexlet-boilerplates/nodejs-package#50]
Нужно исправить версию с `v3` на `v3.0.0`, чтобы экшн не валился как тут https://github.com/hexlet-boilerplates/nodejs-package/actions/runs/1842948635

```
Error: paambaati/codeclimate-action/v3/action.yml:
[35](https://github.com/hexlet-boilerplates/nodejs-package/runs/5189321467?check_suite_focus=true#step:1:35)
Error: paambaati/codeclimate-action/v3/action.yml: (Line: 30, Col: 51, Idx: 902) - (Line: 30, Col: 80, Idx: 931): While parsing a block mapping, did not find expected key.
[36](https://github.com/hexlet-boilerplates/nodejs-package/runs/5189321467?check_suite_focus=true#step:1:36)
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
[37](https://github.com/hexlet-boilerplates/nodejs-package/runs/5189321467?check_suite_focus=true#step:1:37)
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
[38](https://github.com/hexlet-boilerplates/nodejs-package/runs/5189321467?check_suite_focus=true#step:1:38)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
[39](https://github.com/hexlet-boilerplates/nodejs-package/runs/5189321467?check_suite_focus=true#step:1:39)
Error: Fail to load paambaati/codeclimate-action/v3/action.yml
```

Пример из моего проекта:
До: https://github.com/gomez-git/backend-project-lvl2/actions/runs/2275171659
После: https://github.com/gomez-git/backend-project-lvl2/actions/runs/2275244726

**Comment by gomez-git** [comment]
Еще можно секреты вынести в общий env, работает:
https://github.com/gomez-git/js-ini-parser/actions/runs/2283916632

**Comment by dzencot** [comment]
Это было поправлено https://github.com/hexlet-boilerplates/nodejs-package/commit/0762b3d4cadc3463f176244067d4c42b30bf688d
Насчет .env мы его не храним в этом репо. По идее это просто заготовка для проекта. Кому-то может не понадобится env и кодклимат
